version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "redissecret"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redissecret", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    image: dograhai/dograh-api:latest
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://:redissecret@redis:6379

      MINIO_ENDPOINT: minio:9000
      MINIO_PUBLIC_ENDPOINT: http://ggbyswsezpo5fj5n4jd4xku5.147.93.108.76.sslip.io
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

      OSS_JWT_SECRET: ${OSS_JWT_SECRET}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

    networks:
      - app-network
    ports:
      - "8001:8000"

  ui:
    image: dograhai/dograh-ui:latest
    environment:
      # 🔥 KEY CHANGE: USE SAME DOMAIN
      BACKEND_URL: http://ggbyswsezpo5fj5n4jd4xku5.147.93.108.76.sslip.io

      NEXTAUTH_URL: http://ggbyswsezpo5fj5n4jd4xku5.147.93.108.76.sslip.io
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_TRUST_HOST: "true"

      OSS_JWT_SECRET: ${OSS_JWT_SECRET}

      NEXTAUTH_DISABLE_SECURE_COOKIES: "true"
      NODE_ENV: development

    depends_on:
      api:
        condition: service_started

    ports:
      - "3010:3010"

    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  app-network:
    driver: bridge
