version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "redissecret"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redissecret", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    image: dograhai/dograh-api:latest
    volumes:
      - shared-tmp:/tmp
    environment:
      ENVIRONMENT: production
      LOG_LEVEL: INFO

      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://:redissecret@redis:6379

      MINIO_ENDPOINT: minio:9000
      MINIO_PUBLIC_ENDPOINT: http://m17my2pkfkwpejfxqqd4nn20.147.93.108.76.sslip.io
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: voice-audio
      MINIO_SECURE: "false"

      OSS_JWT_SECRET: ${OSS_JWT_SECRET}

      ENABLE_TELEMETRY: "true"
      POSTHOG_API_KEY: "phc_ItizB1dP6yv7ZYobbcqrpxTdbomDA8hJFSEmAMdYvIr"
      POSTHOG_HOST: "https://us.i.posthog.com"

      TURN_HOST: ${TURN_HOST}
      TURN_SECRET: ${TURN_SECRET}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

    ports:
      - "8001:8000"
    networks:
      - app-network

  ui:
    image: dograhai/dograh-ui:latest
    environment:
      BACKEND_URL: http://wt01e8vc1696jqxzuvyvk1xp.147.93.108.76.sslip.io
      NEXTAUTH_URL: http://ggbyswsezpo5fj5n4jd4xku5.147.93.108.76.sslip.io
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_TRUST_HOST: "true"

      NODE_ENV: production
      ENABLE_TELEMETRY: "true"

      POSTHOG_KEY: "phc_ItizB1dP6yv7ZYobbcqrpxTdbomDA8hJFSEmAMdYvIr"
      POSTHOG_HOST: "https://us.posthog.com"

    depends_on:
      api:
        condition: service_started

    ports:
      - "3010:3010"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  minio_data:
  shared-tmp:

networks:
  app-network:
    driver: bridge
